// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meancxdnfqbzbkjrkazd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYW5jeGRuZnFiemJranJrYXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDkyMjgsImV4cCI6MjA3MjEyNTIyOH0.M_EahftT-G7TjXym8pSLLZ0uATdNaEWEoDJzDXos3RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});